CREATE TABLE [dbo].[Laborers]
(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(120) NOT NULL,
	MiddleName NVARCHAR(120) NULL,
	LastName NVARCHAR(120) NULL,
	Email NVARCHAR(120) NOT NULL,
	Username NVARCHAR(120) NOT NULL,
	[Password] NVARCHAR(120) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy NVARCHAR(120) NOT NULL DEFAULT 'AUTO',
	UpdatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy NVARCHAR(120) NOT NULL DEFAULT 'AUTO'
)
