CREATE TABLE [dbo].[Projects]
(	ID INT NOT NULL PRIMARY KEY IDENTITY,
	LongName NVARCHAR(250) NOT NULL,
	ShortName NVARCHAR(120) NOT NULL,
	[Key] NVARCHAR(20) NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy NVARCHAR(120) NOT NULL DEFAULT 'AUTO',
	UpdatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy NVARCHAR(120) NOT NULL DEFAULT 'AUTO'
)
