CREATE TABLE [dbo].[TimeEntries]
(	ID INT NOT NULL PRIMARY KEY IDENTITY,
	LaborerID INT NOT NULL,
	WorkItemID INT NOT NULL,
	StartWork DATETIME NULL,
	EndWork DATETIME NULL,
	Accomplishment NVARCHAR(MAX) NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy NVARCHAR(120) NOT NULL DEFAULT 'AUTO',
	UpdatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy NVARCHAR(120) NOT NULL DEFAULT 'AUTO', 
    CONSTRAINT [FK_TimeEntries_ToLaborers] FOREIGN KEY ([LaborerID]) REFERENCES [Laborers]([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_TimeEntries_ToWorkItems] FOREIGN KEY ([WorkItemID]) REFERENCES [WorkItems]([ID]) ON DELETE CASCADE,
)
