using Microsoft.AspNetCore.Components;
using Radzen.Blazor;
using TimeKeeper.Domain.Models;

namespace TimeKeeper.App.Components;

public partial class TimeEntryEditorComponent : CbComponentBase
{
    #region parameters

    /// <summary>
    /// Gets or sets the time entry to be loaded and displayed by the component.
    /// </summary>
    [Parameter]
    public TimeEntry? LoadedTimeEntry { get; set; }

    /// <summary>
    ///  Gets or sets the callback that is invoked when the loaded time entry changes.
    /// </summary>
    /// <remarks>
    ///  Use this event to respond to changes in the loaded time entry, such as updating UI elements
    ///  or triggering additional logic when a new time entry is loaded.
    /// </remarks>
    [Parameter]
    public EventCallback<TimeEntry> LoadedTimeEntryChanged { get; set; }

    /// <summary>
    ///  Gets or sets the callback that is invoked when the save action is triggered for a time entry.
    /// </summary>
    /// <remarks>
    ///  The callback receives the current time entry as its parameter. Assign this property to handle
    ///  save events from the parent component.
    /// </remarks>
    [Parameter]
    public EventCallback<TimeEntry> OnSaveClicked { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether dialog action buttons are displayed.
    /// </summary>
    [Parameter]
    public bool ShowDialogButtons { get; set; } = false;

    #endregion parameters

    #region properties

    /// <summary>
    /// Gets or sets a value indicating whether the end date should be displayed.
    /// </summary>
    private bool DisplayEndDate { get; set; } = true;

    /// <summary>
    ///  Gets or sets a value indicating whether the start date should be displayed.
    /// </summary>
    private bool DisplayStartDate { get; set; } = true;

    /// <summary>
    ///  Gets a value indicating whether the currently loaded time entry is new and has not been 
    ///  assigned an identifier.
    /// </summary>
    private bool IsNewTimeEntry => this.LoadedTimeEntry?.Id == 0;

    #endregion properties

    #region fields
    #endregion fields

    #region data

    /// <summary>
    ///  Creates a new time entry for the currently loaded user and time entry context.
    /// </summary>
    /// <remarks>
    ///  If no time entry is loaded or no user is logged in, the operation will not create a new time
    ///  entry and returns <see langword="false"/>. On success, updates the loaded time entry with 
    ///  the newly created entry, including any new identifiers assigned by the data store.
    /// </remarks>
    /// <returns>
    ///  A task that represents the asynchronous operation. The task result is <see langword="true"/> 
    ///  if the time entry was successfully created; otherwise, <see langword="false"/>.
    /// </returns>
    private async Task<bool> CreateNewTimeEntry()
    {
        // If the LoadedTimeEntry or User are null then we cannot create a new time entry. 
        //
        TimeEntry loadedTimeEntry = this.EnsureTimeEntryIsLoaded("A time entry must be loaded to create a new time entry.");
        Laborer user              = this.EnsureUserIsLoaded("A user must be logged in to create a new time entry.");

        // initialize the return value to false. We will set it to true if we successfully create a
        // new time entry.
        //
        bool result          = false;
        TimeEntry? timeEntry = await base.TimeEntrySvc.CreateNewTimeEntry(loadedTimeEntry, user);

        // If the time entry was successfully created, update the LoadedTimeEntry with the new time entry
        // that was returned from the service. This will update the UI with any new information such as the
        // new time entry id that was generated by the database. We also set the result to true to indicate
        // that the time entry was successfully created.
        //
        if (timeEntry != null)
        {
            this.LoadedTimeEntry = timeEntry;
            this.LoadedTimeEntry.TakeSnapshot();
            result = true;
        }

        return result;
    }

    /// <summary>
    ///  Attempts to delete the currently loaded time entry for the logged-in user.
    /// </summary>
    /// <remarks>
    ///  This method requires that a time entry is loaded and a user is logged in before it can
    ///  perform the deletion. If either is not available, the operation will not proceed.
    /// </remarks>
    /// <returns>
    ///  A task that represents the asynchronous operation. The task result is <see langword="true"/> 
    ///  if the time entry was successfully deleted; otherwise, <see langword="false"/>.
    /// </returns>
    private async Task<bool> DeleteTimeEntry()
    {
        // If the LoadedTimeEntry or User are null then we cannot delete the time entry. 
        //
        TimeEntry loadedTimeEntry = this.EnsureTimeEntryIsLoaded("A time entry must be loaded to update an existing time entry.");
        Laborer user = this.EnsureUserIsLoaded("A user must be logged in to update an existing time entry.");

        // Initialize the return value to false. We will set it to true if we successfully delete
        // the Time Entry
        //
        bool result = await base.TimeEntrySvc.DeleteTimeEntry(loadedTimeEntry, user.Username);
        return result;
    }

    /// <summary>
    ///  Saves the specified time entry by creating a new record or updating an existing one, and 
    ///  notifies subscribers of the change.
    /// </summary>
    /// <remarks>
    ///  This method raises the LoadedTimeEntryChanged event after saving, allowing subscribers to
    ///  refresh related data or UI. If the time entry is new, a new record is created; otherwise, 
    ///  the existing record is updated.
    /// </remarks>
    /// <param name="timeEntry">
    ///  The time entry to save. Cannot be null and must be valid.
    /// </param>
    /// <returns>
    ///  A task that represents the asynchronous save operation.
    /// </returns>
    /// <exception cref="Exception">
    ///  Thrown if the time entry is not valid.
    /// </exception>
    private async Task SaveTimeEntry(TimeEntry timeEntry)
    {
        // Perform some validation on the time entry before we attempt to save it. If the time entry
        // is not valid, throw an exception.
        //
        ArgumentNullException.ThrowIfNull(timeEntry, nameof(timeEntry));
        bool isValid = timeEntry?.IsValid() ?? false;
        if (!isValid) throw new Exception("Invalid Time Entry");

        // If this is a NEW time entry then run the routine to create a new TimeEntry record.
        //
        if (this.IsNewTimeEntry)
        {
            await this.CreateNewTimeEntry();
        }

        // Otherwise, update the existing TimeEntry record.
        //
        else
        {
            await this.UpdateTimeEntry();
        }

        // Fire event handler to notify any subscribers that the time entry has been updated. This
        // will allow the parent component to refresh any data or UI that is bound to the time entry.
        //
        await LoadedTimeEntryChanged.InvokeAsync(timeEntry);

    }

    /// <summary>
    ///  Attempts to update the currently loaded time entry with the latest information for the 
    ///  logged-in user.
    /// </summary>
    /// <remarks>
    ///  This method requires that both a time entry is loaded and a user is logged in. If either 
    ///  is not available, the update operation will not proceed and the method returns false. 
    ///  Upon a successful update, the loaded time entry is refreshed with the persisted data, 
    ///  ensuring the UI reflects the latest state.
    /// </remarks>
    /// <returns>
    ///  true if the time entry was successfully updated; otherwise, false.
    /// </returns>
    private async Task<bool> UpdateTimeEntry()
    {
        // If the LoadedTimeEntry or User are null then we cannot update an existing time entry. 
        //
        TimeEntry loadedTimeEntry = this.EnsureTimeEntryIsLoaded("A time entry must be loaded to update an existing time entry.");
        Laborer user              = this.EnsureUserIsLoaded("A user must be logged in to update an existing time entry.");
        
        // initialize the return value to false. We will set it to true if we successfully create a
        // new time entry.
        //
        bool result          = false;
        TimeEntry? timeEntry = await base.TimeEntrySvc.UpdateTimeEntry(loadedTimeEntry, user);

        // If the time entry was successfully saved, update the LoadedTimeEntry with the persisted
        // time entry that was returned from the service. This will update the UI with any new
        // information. We also set the result to true to indicate that the time entry was successfully
        // updated.
        //
        if (timeEntry != null)
        {
            this.LoadedTimeEntry = timeEntry;
            this.LoadedTimeEntry.TakeSnapshot();
            result = true;
        }

        return result;
    }

    #endregion data

    #region lifecycle
    #endregion lifecycle

    #region event handlers

    /// <summary>
    ///  Opens a dialog that allows the user to select or change the work item associated with the 
    ///  current time entry.
    /// </summary>
    /// <remarks>
    ///  The method requires that a time entry is loaded before it can be used. The dialog enables
    ///  users to select a work item, and updates the associated work item for the current time entry 
    ///  upon selection.
    /// </remarks>
    /// <returns>
    ///  A task that represents the asynchronous operation of opening the work item selection dialog.
    /// </returns>
    private async Task OnSelectWorkItemClick()
    {
        TimeEntry timeEntry = this.EnsureTimeEntryIsLoaded("A time entry must be loaded to manage associated WorkItem(s).");

        var dialogOptions = base.GetDialogOptions("50rem", "16rem", true, true);
        var parameters    = new Dictionary<string, object>();
            parameters.Add("OpenInDialog", true);
            parameters.Add("SelectedWorkItem", timeEntry.WorkItem ?? new WorkItem());
            parameters.Add("OnWorkItemChanged", EventCallback.Factory.Create<WorkItem>(this, WorkItemListComponent_OnWorkItemChanged));

        await this.DialogSvc!.OpenAsync<WorkItemListComponent>($"Select WorkItem",
            parameters,
            dialogOptions);
    }

    /// <summary>
    ///  Handles changes to the end work time and triggers the LoadedTimeEntryChanged event if a 
    ///  delegate is assigned.
    /// </summary>
    /// <param name="endWork">
    ///  The new end work time value. May be null to indicate no end time is set.
    /// </param>
    /// <returns>
    ///  A task that represents the asynchronous operation.
    /// </returns>
    private async Task OnEndWorkChange(DateTime? endWork)
    {
        if (this.LoadedTimeEntryChanged.HasDelegate)
        {
            await this.LoadedTimeEntryChanged.InvokeAsync(this.LoadedTimeEntry);
        }
    }

    /// <summary>
    ///  Handles changes to the start work time and triggers the LoadedTimeEntryChanged event if a 
    ///  delegate is assigned.
    /// </summary>
    /// <param name="startWork">
    ///  The new start work time value. May be null to indicate no start time is set.
    /// </param>
    /// <returns>
    ///  A task that represents the asynchronous operation.
    /// </returns>
    private async Task OnStartWorkChange(DateTime? startWork)
    {
        if (this.LoadedTimeEntryChanged.HasDelegate)
        {
            await this.LoadedTimeEntryChanged.InvokeAsync(this.LoadedTimeEntry);
        }
    }

    /// <summary>
    ///  Handles changes to the accomplishment text and triggers the LoadedTimeEntryChanged event 
    ///  if a delegate is assigned.
    /// </summary>
    /// <param name="text">
    ///  The new accomplishment text entered by the user.
    /// </param>
    /// <returns>
    ///  A task that represents the asynchronous operation.
    /// </returns>
    private async Task OnAccomplishmentChange(string text)
    {
        if (this.LoadedTimeEntryChanged.HasDelegate)
        {
            await this.LoadedTimeEntryChanged.InvokeAsync(this.LoadedTimeEntry);
        }
    }

    /// <summary>
    /// Handles changes to the selected work item and updates the associated time entry accordingly.
    /// </summary>
    /// <remarks>
    ///  This method updates the currently loaded time entry to reference the new work item and 
    ///  notifies any subscribers of the change. It also updates the user interface to reflect 
    ///  the new work item details.
    /// </remarks>
    /// <param name="item">
    ///  The work item that has been selected or changed. Cannot be null.
    /// </param>
    private async Task WorkItemListComponent_OnWorkItemChanged(WorkItem item)
    {
        if (this.LoadedTimeEntry != null)
        {
            // update the bound time entry with the new work item this will trigger the UI to
            // update and show the new work item details. We also need to update the work item
            // id on the time entry so that when we save it, it will be associated with the
            // correct work item in the database.
            //
            this.LoadedTimeEntry.WorkItem   = item;
            this.LoadedTimeEntry.WorkItemId = item.Id;

            // If the StartWork of the TimeEntry is undefined then let's set it to a default value.
            // The EndWork property is ok to be left NULL as the user may be creating a new active
            // TimeEntry. 
            // 
            this.LoadedTimeEntry.StartWork ??= DateTime.Now;

            // Notify the subscriber that the Loaded TimeEntry has changed (but those changes are 
            // temporary until saved to the datastore.
            //
            if (this.LoadedTimeEntryChanged.HasDelegate)
            {
                await this.LoadedTimeEntryChanged.InvokeAsync(this.LoadedTimeEntry);
            }
        }

        base.StateHasChanged();
    }

    #endregion event handlers

    #region private

    /// <summary>
    ///  Ensures that a time entry is loaded and returns it.
    /// </summary>
    /// <param name="errMsg">
    ///  The error message to include in the exception if no time entry is loaded. Cannot be null.
    /// </param>
    /// <returns>
    ///  The loaded time entry.
    /// </returns>
    /// <exception cref="ArgumentException">
    ///  Thrown if no time entry is loaded.
    /// </exception>
    private TimeEntry EnsureTimeEntryIsLoaded(string errMsg)
    {
        if (this.LoadedTimeEntry == null) throw new ArgumentException(errMsg);
        else return this.LoadedTimeEntry;
    }

    /// <summary>
    ///  Ensures that a user is loaded in the current session and returns the user.
    /// </summary>
    /// <param name="errMsg">
    ///  The error message to include in the exception if no user is loaded. Cannot be null.
    /// </param>
    /// <returns>
    ///  The current user associated with the session.
    /// </returns>
    /// <exception cref="ArgumentException">
    ///  Thrown if no user is loaded in the session.
    /// </exception>
    private Laborer EnsureUserIsLoaded(string errMsg)
    {
        if (base.SessionService?.User == null) throw new ArgumentException(errMsg);
        else return base.SessionService.User;
    }

    /// <summary>
    ///  Finalizes the end work timestamp for the current time entry if it has not already been set.
    /// </summary>
    /// <remarks>
    ///  If the end work timestamp is already set, this method leaves it unchanged. Otherwise, it sets
    ///  the end work timestamp to the current system time.
    /// </remarks>
    /// <returns>
    ///  The updated time entry with the end work timestamp populated if it was previously unset.
    /// </returns>
    private TimeEntry FinalizeTimeEntry()
    {
        TimeEntry loadedTimeEntry = this.EnsureTimeEntryIsLoaded("");
        
        // If the End Work Timestamp is not populated then populate it with the current time.
        //
        if(!loadedTimeEntry.EndWork.HasValue)
        {
            loadedTimeEntry.EndWork = DateTime.Now;
        }

        return loadedTimeEntry;
    }

    /// <summary>
    ///  Validates whether the currently loaded time entry meets the requirements for saving.
    /// </summary>
    /// <remarks>
    ///  If the validation fails, an error notification is sent to inform the user of the
    ///  specific issue. The time entry must not be null, must be associated with a work item, 
    ///  and must pass all internal validity checks.
    /// </remarks>
    /// <returns>
    ///  true if the loaded time entry is valid and can be saved; otherwise, false.
    /// </returns>
    private bool TimeEntryIsValid()
    {
        //return await Task.Run(()=> {

            bool isValid = true;
        //    var notificationMessage = new NotificationMessage()
        //    {
        //        Severity = NotificationSeverity.Error,
        //        Summary = "Time Entry Save Failed",
        //        Duration = 5000,
        //        CloseOnClick = true
        //    };

            if (this.LoadedTimeEntry == null)
            {
                isValid = false;
                //notificationMessage.Detail = "The Time Entry cannot be null. Initialize the Time Entry to save.";
            }

            else if(this.LoadedTimeEntry.WorkItemId == default(int))
            {
                isValid = false;
                //notificationMessage.Detail = "The Time Entry must be associated with a Workitem.";
            }

            else if(!this.LoadedTimeEntry.IsValid())
            {
                isValid = false;
                //notificationMessage.Detail = "The Time Entry is not valid.";
            }

            //if(!isValid)
            //{
            //    base.NotificationSvc.Notify(notificationMessage);
            //}

            return isValid;
        //});
    }

    #endregion private

    #region event hanlders

    /// <summary>
    ///  Handles the cancel action for the time entry dialog, deleting the current time entry and 
    ///  closing the dialog.
    /// </summary>
    /// <remarks>
    ///  This method deletes the loaded time entry, resets the loaded entry state, closes the dialog,
    ///  and triggers the save event. Use this method to cancel and remove the current time entry 
    ///  from the dialog.
    /// </remarks>
    /// <returns>
    ///  A task that represents the asynchronous operation.
    /// </returns>
    private async Task OnDiscardTimeEntryClick()
    {
        TimeEntry loadedTimeEntry = this.EnsureTimeEntryIsLoaded("");
        _ = await this.DeleteTimeEntry();

        this.LoadedTimeEntry = null;
        base.DialogSvc.Close();
        await this.OnSaveClicked.InvokeAsync();
    }

    /// <summary>
    ///  Handles the save operation for a time entry and optionally submits the associated work item 
    ///  for review based on the selected button item.
    /// </summary>
    /// <remarks>
    ///  If the editor is displayed in a dialog, the dialog is closed after saving. When the user
    ///  selects the submit option, the associated work item's review status is updated and persisted.
    /// </remarks>
    /// <param name="item">
    ///  The split button item that was clicked, determining whether to perform a standard save or 
    ///  submit the work item for review. If the item's Value is "submit", the work item is submitted 
    ///  for review.
    /// </param>
    /// <returns>
    ///  A task that represents the asynchronous operation.
    /// </returns>
    private async Task OnSaveClick(RadzenSplitButtonItem item)
    {
        // If item argument is null then it defaults to a "Save"
        // 
        string action = item == null ? "save" : item.Value.ToLower();

        // If the save request is to end the TimeEntry without a PR then process the TimeEntry to
        // make sure that an appropriate EndWork timestamp has been applied. Otherwise retrieve a
        // reference to the LoadedTimeEntry.
        //
        TimeEntry loadedTimeEntry = (action == "stopwork") ? this.FinalizeTimeEntry() : 
                                                             this.EnsureTimeEntryIsLoaded("");

        // Save the TimeEntry record
        //
        await this.SaveTimeEntry(loadedTimeEntry);

        // If the user clicked on the "Submit for Review" Button update the WorkItem status
        //
        if(item != null && item.Value == "submit")
        {
            // call to submit the WorkItem PR
            //
            if (loadedTimeEntry.WorkItem != null)
            {
                loadedTimeEntry.WorkItem.IsInReview = true;
                await base.WorkItemSvc.UpdateWorkItem(loadedTimeEntry.WorkItem);
            }
        }

        // If the Editor is being displayed in a Dialog box. Close it after saving
        //
        if(this.ShowDialogButtons) base.DialogSvc.Close();

        // Notify subscribers that the Save button was clicked.
        //
        await this.OnSaveClicked.InvokeAsync();
    }

    /// <summary>
    ///  Handles the save action for a new time entry, persists the entry, closes the dialog if open, 
    ///  and notifies subscribers.
    /// </summary>
    /// <returns>
    ///  A task that represents the asynchronous operation.
    /// </returns>
    private async Task OnSaveNewClick()
    {
        TimeEntry loadedTimeEntry = this.EnsureTimeEntryIsLoaded("");

        // Save the TimeEntry record
        //
        await this.SaveTimeEntry(loadedTimeEntry);

        // If the Editor is being displayed in a Dialog box. Close it after saving
        //
        if (this.ShowDialogButtons) base.DialogSvc.Close();

        // Notify subscribers that the Save button was clicked.
        //
        await this.OnSaveClicked.InvokeAsync();
    }

    #endregion event handlers

}