<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<LangVersion>14.0</LangVersion>
	<UserSecretsId>2c358e2b-039c-43d1-9053-77995aea3380</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeKeeper.Domain\TimeKeeper.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Api\Extensions\" />
    <Folder Include="Api\Utilities\" />
    <Folder Include="NewComponents\WorkItemComponents\" />
    <Folder Include="wwwroot\css\Pages\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="8.4.1" />
  </ItemGroup>

</Project>
